// Fixture data for the helpdesk. There is no server, so the rows live here.

export const currentAgent = 'Sam Rivera'

// Status colour. Only status, priority and SLA state carry colour here.
export const statusTheme: Record<string, string> = {
  Open: 'red',
  Replied: 'blue',
  Resolved: 'green',
  Paused: 'gray',
}

// Priority dot colour.
export const priorityDot: Record<string, string> = {
  Urgent: 'bg-surface-red-7',
  High: 'bg-surface-amber-7',
  Medium: 'bg-surface-gray-7',
  Low: 'bg-surface-gray-4',
}

// SLA state to text colour. `met` and `breached` read as pass and fail against
// the target. `pending` is still counting down. `none` means no target applies.
export const slaTextClass: Record<string, string> = {
  met: 'text-ink-green-5',
  breached: 'text-ink-red-5',
  pending: 'text-ink-gray-5',
  none: 'text-ink-gray-4',
}

export const nav = [
  { label: 'Tickets', icon: 'lucide-ticket', to: '/', count: 24 },
  { label: 'Customers', icon: 'lucide-building-2', to: '/customers' },
  { label: 'Contacts', icon: 'lucide-contact', to: '/contacts' },
  { label: 'Agents', icon: 'lucide-headset', to: '/agents' },
  { label: 'Knowledge base', icon: 'lucide-book-open', to: '/knowledge-base' },
  {
    label: 'Canned responses',
    icon: 'lucide-message-square-text',
    to: '/canned-responses',
  },
]

// Saved views. Each one owns a path, so no route takes a parameter.
export const views = [
  { label: 'My open tickets', to: '/my-open-tickets' },
  { label: 'Urgent', to: '/urgent' },
  { label: 'Unassigned', to: '/unassigned' },
  { label: 'Solved this week', to: '/solved-this-week' },
]

export const viewLabel: Record<string, string> = {
  '/': 'Tickets',
  '/my-open-tickets': 'My open tickets',
  '/urgent': 'Urgent',
  '/unassigned': 'Unassigned',
  '/solved-this-week': 'Solved this week',
}

// One filter per saved view. The main list has none, so it falls back to tabs.
export const viewFilter: Record<string, (ticket: any) => boolean> = {
  '/my-open-tickets': (t) =>
    t.agent === currentAgent && ['Open', 'Replied'].includes(t.status),
  '/urgent': (t) => t.priority === 'Urgent',
  '/unassigned': (t) => !t.agent,
  '/solved-this-week': (t) => t.status === 'Resolved' && t.modified <= 7 * 24 * 60,
}

// `firstResponse` and `resolution` mirror a helpdesk SLA: `label` is the
// elapsed or remaining time, `state` drives the colour.
export const tickets = [
  {
    id: 1024,
    subject: 'Cannot connect custom domain to my site',
    customer: 'Acme Corp',
    status: 'Open',
    priority: 'Urgent',
    agent: 'Priya Nair',
    agentImage: 'https://i.pravatar.cc/150?img=8',
    firstResponse: { label: 'Due 8 m', state: 'pending' },
    resolution: { label: 'Due 3 h', state: 'pending' },
    modified: 12,
    modifiedLabel: '12 m',
  },
  {
    id: 1023,
    subject: 'Invoice shows wrong billing address',
    customer: 'Globex',
    status: 'Replied',
    priority: 'High',
    agent: 'Evan You',
    agentImage: 'https://avatars.githubusercontent.com/u/499550?v=4',
    firstResponse: { label: '6 m', state: 'met' },
    resolution: { label: 'Due 5 h', state: 'pending' },
    modified: 45,
    modifiedLabel: '45 m',
  },
  {
    id: 1022,
    subject: 'Webhook deliveries failing since yesterday',
    customer: 'Initech',
    status: 'Open',
    priority: 'High',
    agent: 'Sam Rivera',
    agentImage: 'https://i.pravatar.cc/150?img=15',
    firstResponse: { label: 'Overdue 20 m', state: 'breached' },
    resolution: { label: 'Due 1 h', state: 'pending' },
    modified: 120,
    modifiedLabel: '2 h',
  },
  {
    id: 1021,
    subject: 'How do I export all my data?',
    customer: 'Hooli',
    status: 'Replied',
    priority: 'Medium',
    agent: 'Ana Costa',
    agentImage: 'https://i.pravatar.cc/150?img=25',
    firstResponse: { label: '18 m', state: 'met' },
    resolution: { label: 'Due 1 d', state: 'pending' },
    modified: 300,
    modifiedLabel: '5 h',
  },
  {
    id: 1017,
    subject: 'Payment gateway returns 500 on checkout',
    customer: 'Wayne Enterprises',
    status: 'Open',
    priority: 'Urgent',
    agent: 'Leo Park',
    agentImage: 'https://i.pravatar.cc/150?img=33',
    firstResponse: { label: 'Due 4 m', state: 'pending' },
    resolution: { label: 'Due 2 h', state: 'pending' },
    modified: 5,
    modifiedLabel: '5 m',
  },
  {
    id: 1016,
    subject: 'API rate limit hit unexpectedly',
    customer: 'Soylent',
    status: 'Replied',
    priority: 'High',
    agent: 'Mara Singh',
    agentImage: 'https://i.pravatar.cc/150?img=45',
    firstResponse: { label: '11 m', state: 'met' },
    resolution: { label: 'Due 6 h', state: 'pending' },
    modified: 30,
    modifiedLabel: '30 m',
  },
  {
    id: 1015,
    subject: 'Cannot invite new team members',
    customer: 'Cyberdyne',
    status: 'Open',
    priority: 'Medium',
    agent: 'Ana Costa',
    agentImage: 'https://i.pravatar.cc/150?img=25',
    firstResponse: { label: 'Overdue 5 m', state: 'breached' },
    resolution: { label: 'Due 9 h', state: 'pending' },
    modified: 75,
    modifiedLabel: '1 h',
  },
  {
    id: 1014,
    subject: 'Emails landing in the spam folder',
    customer: 'Tyrell Corp',
    status: 'Replied',
    priority: 'Medium',
    agent: 'Sam Rivera',
    agentImage: 'https://i.pravatar.cc/150?img=15',
    firstResponse: { label: '24 m', state: 'met' },
    resolution: { label: 'Due 12 h', state: 'pending' },
    modified: 210,
    modifiedLabel: '3 h 30 m',
  },
  {
    id: 1013,
    subject: 'Report export times out for large datasets',
    customer: 'Massive Dynamic',
    status: 'Replied',
    priority: 'High',
    agent: 'Leo Park',
    agentImage: 'https://i.pravatar.cc/150?img=33',
    firstResponse: { label: '9 m', state: 'met' },
    resolution: { label: 'Due 4 h', state: 'pending' },
    modified: 260,
    modifiedLabel: '4 h',
  },
  {
    id: 1012,
    subject: 'Typo in the onboarding welcome email',
    customer: 'Wonka Industries',
    status: 'Open',
    priority: 'Low',
    agent: 'Mara Singh',
    agentImage: 'https://i.pravatar.cc/150?img=45',
    firstResponse: { label: 'Due 2 d', state: 'pending' },
    resolution: { label: 'Due 5 d', state: 'pending' },
    modified: 480,
    modifiedLabel: '8 h',
  },
  {
    id: 1020,
    subject: 'Two-factor authentication reset request',
    customer: 'Umbrella Labs',
    status: 'Paused',
    priority: 'Medium',
    agent: 'Priya Nair',
    agentImage: 'https://i.pravatar.cc/150?img=8',
    firstResponse: { label: '14 m', state: 'met' },
    resolution: { label: 'On hold', state: 'none' },
    modified: 1440,
    modifiedLabel: '1 d',
  },
  {
    id: 1011,
    subject: 'Production site down after last deploy',
    customer: 'Oscorp',
    status: 'Replied',
    priority: 'Urgent',
    agent: 'Sam Rivera',
    agentImage: 'https://i.pravatar.cc/150?img=15',
    firstResponse: { label: '3 m', state: 'met' },
    resolution: { label: 'Overdue 40 m', state: 'breached' },
    modified: 1500,
    modifiedLabel: '1 d',
  },
  {
    id: 1019,
    subject: 'Feature request: dark mode for the portal',
    customer: 'Pied Piper',
    status: 'Resolved',
    priority: 'Low',
    agent: 'Evan You',
    agentImage: 'https://avatars.githubusercontent.com/u/499550?v=4',
    firstResponse: { label: '32 m', state: 'met' },
    resolution: { label: '1 d 4 h', state: 'met' },
    modified: 2880,
    modifiedLabel: '2 d',
  },
  {
    id: 1010,
    subject: 'Refund not reflected on my statement',
    customer: 'Gringotts',
    status: 'Resolved',
    priority: 'Medium',
    agent: 'Ana Costa',
    agentImage: 'https://i.pravatar.cc/150?img=25',
    firstResponse: { label: '19 m', state: 'met' },
    resolution: { label: '6 h 12 m', state: 'met' },
    modified: 3600,
    modifiedLabel: '2 d',
  },
  {
    id: 1018,
    subject: 'SSO login loops back to the sign-in page',
    customer: 'Stark Industries',
    status: 'Resolved',
    priority: 'Urgent',
    agent: 'Sam Rivera',
    agentImage: 'https://i.pravatar.cc/150?img=15',
    firstResponse: { label: '52 m', state: 'breached' },
    resolution: { label: '2 d 1 h', state: 'breached' },
    modified: 4320,
    modifiedLabel: '3 d',
  },
  {
    id: 1009,
    subject: 'Update company logo on generated invoices',
    customer: 'Nakatomi',
    status: 'Resolved',
    priority: 'Low',
    agent: 'Leo Park',
    agentImage: 'https://i.pravatar.cc/150?img=33',
    firstResponse: { label: '41 m', state: 'met' },
    resolution: { label: '3 d 2 h', state: 'met' },
    modified: 5760,
    modifiedLabel: '4 d',
  },
]
